SPRING_DATA_MONGODB_INETADDRESS: mongodb://mongo_db:27017
SPRING_DATA_MONGODB_PORT: 27017
SPRING_DATA_MONGODB_DATABASE: Readingisgood
SPRING_APPLICATION_NAME: reading-is-good
JWT_SECRET: secretkey

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  data:
    mongodb:
      database: ${SPRING_DATA_MONGODB_DATABASE}
      inetAddresses: ${SPRING_DATA_MONGODB_INETADDRESS}
      authenticationDatabase: admin
      port: ${SPRING_DATA_MONGODB_PORT}

jwt:
  secret: ${JWT_SECRET}
